#!/bin/sh

set -o errexit -o nounset -o pipefail
set -o xtrace

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    against=$(git hash-object -t tree /dev/null)
fi

exec 1>&2

files=$(git diff --cached --name-only --diff-filter=AMT $against | grep '.*\.[eh]rl$')
./edent $files
git add $files
