#! /usr/bin/env bash

set -o errexit -o nounset -o pipefail

declare -a TESTS
TESTS=(
    basics
#    hell # known bad cases
    block_case
    block_try
    block_receive )

for TEST in "${TESTS[@]}"; do
    input="tests/${TEST}.erl"
    output="tests/${TEST}.out.erl"

    printf "%0.1s" ={1..100}
    printf "\ntest: %s\ninput: %s\noutput: %s\n\n" "$TEST" "$input" "$output"

    erlc "$input"

    ./edent "$input" "$output"
    diff "$input" "$output"
done
